### ISSUE TITLE
Opening MODIS Aqua nc file is not working

### ISSUE THREAD

**Issue by PMassicotte** [ropensci/tidync#108]
I am trying to open a MODIS Aqua NetCDF file (<https://oceandata.sci.gsfc.nasa.gov/MODIS-Aqua/L3SMI/2010/001/>) using the `tidync` package.

``` r
library(tidync)

tidync("~/Desktop/A20120012012008.L3b_8D_CHL.nc")
#> Error: `distinct()` must use existing variables.
#> x `id` not found in `.data`.
#> x `name` not found in `.data`.
#> x `type` not found in `.data`.
#> x `ndims` not found in `.data`.
#> x `natts` not found in `.data`.
```

Any ideas on why this is not working?

<sup>Created on 2021-02-20 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by matteodefelice** [comment]
Can you post a ncdump - h of the file?

**Comment by mdsumner** [comment]
the file you post is "L3b", which is "Level 3 bin" - tidync can't open these because neither RNetCDF or ncdf4 can access their data.  (though, this context changes all the time so I might be a bit out of date). 

The error message should be better so I'll have a look. 

The folder you share is to the "SMI" "Standard Mapped Image" - there's no L3b in there - but the SMI should all work fine. 

I expect you really don't want the Level 3 bins ... but if you do I can help, with other packages ;)

**Comment by PMassicotte** [comment]
Hi guys and thank you for your replies. I have found out that I could open it assuming it was hdf5 format...

```r
library(rhdf5)
h5ls("~/Desktop/A20120012012008.L3b_8D_CHL.nc")
``` 
I am not sure why.

Based on your message, I was able to open:

- https://oceandata.sci.gsfc.nasa.gov/MODIS-Aqua/Mapped/8-Day/4km/chlor_a/
- https://oceandata.sci.gsfc.nasa.gov/MODIS-Aqua/L3SMI/

I am not sure to understand why the L3B cannot be open.

**Comment by PMassicotte** [comment]
From here: https://oceancolor.gsfc.nasa.gov/docs/format/

> **Each Level-3 binned data product is stored in one or more HDF files.** Each multi-file product includes a main file containing all product-level metadata and data for each bin that are common to all the binned geophysical parameters, and multiple subordinate files, each of which contains data of one binned geophysical parameter for all bins. Subordinate files must be read in conjunction with the associated main file.

It looks like they are using `.nc` files which are in fact HDF files.

**Comment by mdsumner** [comment]
There's two things, compound types (like lists of vectors, or tables) and groups. ncdf4 and RNetCDF do both support groups, these are like a directory of files within a file - but they don't support the compound types (hdf5 tools do support)

**Comment by PMassicotte** [comment]
Thank you for your answer. I will close this.
