### ISSUE TITLE
Guide for groupies?

### ISSUE THREAD

**Issue by mike-lawrence** [ropensci/tidync#109]
Hey there, I'm [working on a package](https://github.com/mike-lawrence/aria) that will be writing NETCDF4 files using the [InferenceData spec](https://arviz-devs.github.io/arviz/getting_started/XarrayforArviZ.html), which includes groups. I'm currently using RNetcdf for this but tidync looks really cool. Happen to know any workarounds for creating nc's with groups?

**Comment by mdsumner** [comment]
No, sorry - I very rarely create nc files. I expect there's something in RNetCDF (I've toyed around with reading I think, definitely not writing). You might look at an HDF5 package (I use rhdf5 from Bioconductor, I think - that landscape changes a fair bit  - but again only for read, I really needed compound types as well as groups).

**Comment by mdsumner** [comment]
(fwiw, a NetCDF 4 file is an HDF5 file, which is insightful if you've never heard that)

**Comment by mike-lawrence** [comment]
Ok, then I'll stick with using RNetCDF when creating then; definitely going to look into tidync for reading/slicing though! Next on my list. 

And yup! I've been using hdf5 for years, inc the zoo of packages (h5, rhdf5, hdf5r, ... ). I'm trying to hew as close to the InferenceData spec as possible, and figured I might run into subtle spec-violations if I didn't use something built for the netcdf4 sub-class specfically. Thanks for your input though! :)
