### ISSUE TITLE
Problems with number of rows after tidying netcdf 

### ISSUE THREAD

**Issue by oousmane** [ropensci/tidync#116]
<details> <summary><strong>Code</strong></summary>

```r
library(tidync)
library(tidyverse)
#---- read netcdf using tidync package

file <- "~/Documents/Ghana/sst.mnmean.nc"
tidync(file) %>% 
  hyper_tibble()
```
</details>

<details> <summary><strong>Problem/Question</strong></summary>

the output is a tibble of 22228724 rows but actually it is. 32408460.
Data Source (1): sst.mnmean.nc ...

Grids (5) <dimension family> : <associated variables> 

[1]   D1,D0,D2 : sst    **ACTIVE GRID** ( **32408460**  values per variable)
[2]   D3,D2    : time_bnds
[3]   D0       : lat
[4]   D1       : lon
[5]   D2       : time

How to fix that?
</details>
<details> <summary><strong>Session Info</strong></summary>

─ Session info ──────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 (2022-04-22)
 os       macOS Monterey 12.5.1
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Africa/Niamey
 date     2022-09-15
 rstudio  2022.11.0-daily+166 Elsbeth Geranium (desktop)
 pandoc   2.11.3.2 @ /usr/local/bin/pandoc

─ Packages ──────────────────────────────────────────────────────
 package     * version    date (UTC) lib source
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.2.0)
 cachem        1.0.6      2021-08-19 [1] CRAN (R 4.2.0)
 callr         3.7.2      2022-08-22 [1] CRAN (R 4.2.0)
 cli           3.3.0      2022-04-25 [1] CRAN (R 4.2.0)
 clipr         0.8.0      2022-02-22 [1] CRAN (R 4.2.0)
 crayon        1.5.1      2022-03-26 [1] CRAN (R 4.2.0)
 curl          4.3.2      2021-06-23 [1] CRAN (R 4.2.0)
 DBI           1.1.3      2022-06-18 [1] CRAN (R 4.2.0)
 devtools      2.4.4      2022-07-20 [1] CRAN (R 4.2.0)
 digest        0.6.29     2021-12-01 [1] CRAN (R 4.2.0)
 dplyr         1.0.10     2022-09-01 [1] CRAN (R 4.2.0)
 ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.2.0)
 fansi         1.0.3      2022-03-24 [1] CRAN (R 4.2.0)
 fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.2.0)
 forcats       0.5.2      2022-08-19 [1] CRAN (R 4.2.0)
 fs            1.5.2      2021-12-08 [1] CRAN (R 4.2.0)
 generics      0.1.3      2022-07-05 [1] CRAN (R 4.2.0)
 glue          1.6.2      2022-02-24 [1] CRAN (R 4.2.0)
 htmltools     0.5.3      2022-07-18 [1] CRAN (R 4.2.0)
 htmlwidgets   1.5.4      2021-09-08 [1] CRAN (R 4.2.0)
 httpuv        1.6.5      2022-01-05 [1] CRAN (R 4.2.0)
 later         1.3.0      2021-08-18 [1] CRAN (R 4.2.0)
 lifecycle     1.0.2      2022-09-09 [1] CRAN (R 4.2.0)
 magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.2.0)
 memoise       2.0.1      2021-11-26 [1] CRAN (R 4.2.0)
 mime          0.12       2021-09-28 [1] CRAN (R 4.2.0)
 miniUI        0.1.1.1    2018-05-18 [1] CRAN (R 4.2.0)
 ncdf4         1.19       2021-12-15 [1] CRAN (R 4.2.0)
 ncmeta        0.3.0      2020-08-27 [1] CRAN (R 4.2.0)
 pillar        1.8.1      2022-08-19 [1] CRAN (R 4.2.0)
 pkgbuild      1.3.1      2021-12-20 [1] CRAN (R 4.2.0)
 pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.2.0)
 pkgload       1.3.0      2022-06-27 [1] CRAN (R 4.2.0)
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.2.0)
 processx      3.7.0      2022-07-07 [1] CRAN (R 4.2.0)
 profvis       0.3.7      2020-11-02 [1] CRAN (R 4.2.0)
 promises      1.2.0.1    2021-02-11 [1] CRAN (R 4.2.0)
 ps            1.7.1      2022-06-18 [1] CRAN (R 4.2.0)
 purrr         0.3.4      2020-04-17 [1] CRAN (R 4.2.0)
 R6            2.5.1      2021-08-19 [1] CRAN (R 4.2.0)
 Rcpp          1.0.9      2022-07-08 [1] CRAN (R 4.2.0)
 remotes       2.4.2      2021-11-30 [1] CRAN (R 4.2.0)
 rlang         1.0.5      2022-08-31 [1] CRAN (R 4.2.0)
 RNetCDF       2.6-1      2022-06-27 [1] CRAN (R 4.2.0)
 rprojroot     2.0.3      2022-04-02 [1] CRAN (R 4.2.0)
 rstudioapi    0.14       2022-08-22 [1] CRAN (R 4.2.0)
 sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.2.0)
 shiny         1.7.2      2022-07-19 [1] CRAN (R 4.2.0)
 stringi       1.7.8      2022-07-11 [1] CRAN (R 4.2.0)
 stringr       1.4.1      2022-08-20 [1] CRAN (R 4.2.0)
 tibble        3.1.8      2022-07-22 [1] CRAN (R 4.2.0)
 tidync      * 0.2.4.9002 2022-09-15 [1] Github (ropensci/tidync@585ed5a)
 tidyr         1.2.1      2022-09-08 [1] CRAN (R 4.2.0)
 tidyselect    1.1.2      2022-02-21 [1] CRAN (R 4.2.0)
 urlchecker    1.0.1      2021-11-30 [1] CRAN (R 4.2.0)
 usethis       2.1.6      2022-05-25 [1] CRAN (R 4.2.0)
 utf8          1.2.2      2021-07-24 [1] CRAN (R 4.2.0)
 vctrs         0.4.1      2022-04-13 [1] CRAN (R 4.2.0)
 withr         2.5.0      2022-03-03 [1] CRAN (R 4.2.0)
 xtable        1.8-4      2019-04-21 [1] CRAN (R 4.2.0)

 [1] /Library/Frameworks/R.framework/Versions/4.2/Resources/library

─────────────────────────────────────────────────────────────────
</details>

**Comment by mdsumner** [comment]
works for me 

``` r
## from ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2/
f <- "../../sst.mnmean.nc" 
library(tidync)
ncmeta::nc_dims(f)
#> # A tibble: 4 × 4
#>      id name  length unlim
#>   <int> <chr>  <dbl> <lgl>
#> 1     0 lat      180 FALSE
#> 2     1 lon      360 FALSE
#> 3     2 time     489 TRUE 
#> 4     3 nbnds      2 FALSE
ncmeta::nc_dims(f) |> dplyr::filter(name %in% c("lon", "lat", "time")) |> dplyr::summarize(prod(length))
#> # A tibble: 1 × 1
#>   `prod(length)`
#>            <dbl>
#> 1       31687200

tidync(f) |> hyper_tibble()
#> # A tibble: 31,687,200 × 4
#>      sst   lon   lat  time
#>    <dbl> <dbl> <dbl> <dbl>
#>  1 -1.79   0.5  89.5 66443
#>  2 -1.79   1.5  89.5 66443
#>  3 -1.79   2.5  89.5 66443
#>  4 -1.79   3.5  89.5 66443
#>  5 -1.79   4.5  89.5 66443
#>  6 -1.79   5.5  89.5 66443
#>  7 -1.79   6.5  89.5 66443
#>  8 -1.79   7.5  89.5 66443
#>  9 -1.79   8.5  89.5 66443
#> 10 -1.79   9.5  89.5 66443
#> # … with 31,687,190 more rows
basename(f)
#> [1] "sst.mnmean.nc"
```



I wonder what's wrong?

**Comment by mdsumner** [comment]
my copy of sst.mnmean.nc might be a bit out of date, I'll check that

**Comment by mdsumner** [comment]
looks ok

```R
curl::curl_download("https://downloads.psl.noaa.gov/Datasets/noaa.oisst.v2/sst.mnmean.nc", "sst.mnmean.nc")
library(tidync)
f <- "sst.mnmean.nc"
ncmeta::nc_dims(f)
ncmeta::nc_dims(f) |> dplyr::filter(name %in% c("lon", "lat", "time")) |> dplyr::summarize(prod(length))

tidync(f) |> hyper_tibble()
basename(f)
```

```
f <- "sst.mnmean.nc"
> ncmeta::nc_dims(f)
# A tibble: 4 × 4
     id name  length unlim
  <int> <chr>  <dbl> <lgl>
1     0 lat      180 FALSE
2     1 lon      360 FALSE
3     2 time     489 TRUE 
4     3 nbnds      2 FALSE
> ncmeta::nc_dims(f) |> dplyr::filter(name %in% c("lon", "lat", "time")) |> dplyr::summarize(prod(length))
# A tibble: 1 × 1
  `prod(length)`
           <dbl>
1       31687200
> tidync(f) |> hyper_tibble()
# A tibble: 31,687,200 × 4
     sst   lon   lat  time
   <dbl> <dbl> <dbl> <dbl>
 1 -1.79   0.5  89.5 66443
 2 -1.79   1.5  89.5 66443
 3 -1.79   2.5  89.5 66443
 4 -1.79   3.5  89.5 66443
 5 -1.79   4.5  89.5 66443
 6 -1.79   5.5  89.5 66443
 7 -1.79   6.5  89.5 66443
 8 -1.79   7.5  89.5 66443
 9 -1.79   8.5  89.5 66443
10 -1.79   9.5  89.5 66443
# … with 31,687,190 more rows
# ℹ Use `print(n = ...)` to see more rows
> basename(f)
[1] "sst.mnmean.nc"
```

**Comment by oousmane** [comment]
Wow, really I don't know what's wrong,  still not okay for me even? prod time*lon*lat lengths is good, but the return number of rows still low than actual. will get mad. I used stars and terra and I got the good result but with tidync no way. I used tidync version ‘0.2.4.9002’

**Comment by gsapijaszko** [comment]
Works for me as well, regardless of package version / R version. Tested with R 4.1.2 & 4.2.2 + tidync 0.2.4 & 0.3.
@oousmane would you try to update/reinstall tidync?

Regards,
Grzegorz

``` r
download.file("https://downloads.psl.noaa.gov/Datasets/noaa.oisst.v2/sst.mnmean.nc", 
              "sst.mnmean.nc", 
              method = "wget", extra = "-c --progress=bar:force")

devtools::install_version("tidync", version = "0.2.4")
#> Downloading package from url: https://cran.rstudio.com//src/contrib/Archive/tidync/tidync_0.2.4.tar.gz
#> Installing package into '/home/sapi/R/x86_64-pc-linux-gnu-library/4.2'
#> (as 'lib' is unspecified)
packageVersion("tidync")
#> [1] '0.2.4'
f <- "sst.mnmean.nc"
tidync::tidync(f) |>
  tidync::hyper_tibble()
#> # A tibble: 31,816,800 × 4
#>      sst   lon   lat  time
#>    <dbl> <dbl> <dbl> <dbl>
#>  1 -1.79   0.5  89.5 66443
#>  2 -1.79   1.5  89.5 66443
#>  3 -1.79   2.5  89.5 66443
#>  4 -1.79   3.5  89.5 66443
#>  5 -1.79   4.5  89.5 66443
#>  6 -1.79   5.5  89.5 66443
#>  7 -1.79   6.5  89.5 66443
#>  8 -1.79   7.5  89.5 66443
#>  9 -1.79   8.5  89.5 66443
#> 10 -1.79   9.5  89.5 66443
#> # … with 31,816,790 more rows

ncmeta::nc_dims(f)
#> # A tibble: 4 × 4
#>      id name  length unlim
#>   <int> <chr>  <dbl> <lgl>
#> 1     0 lat      180 FALSE
#> 2     1 lon      360 FALSE
#> 3     2 time     491 TRUE 
#> 4     3 nbnds      2 FALSE
p1 <- ncmeta::nc_dims(f) |> 
  dplyr::filter(name %in% c("lon", "lat", "time")) |> 
  dplyr::summarize(prod(length))

devtools::install_version("tidync", version = "0.3")
#> Downloading package from url: https://cran.rstudio.com/src/contrib/tidync_0.3.0.tar.gz
#> Installing package into '/home/sapi/R/x86_64-pc-linux-gnu-library/4.2'
#> (as 'lib' is unspecified)
packageVersion("tidync")
#> [1] '0.3.0'
f <- "sst.mnmean.nc"
tidync::tidync(f) |>
  tidync::hyper_tibble()
#> # A tibble: 31,816,800 × 4
#>      sst   lon   lat  time
#>    <dbl> <dbl> <dbl> <dbl>
#>  1 -1.79   0.5  89.5 66443
#>  2 -1.79   1.5  89.5 66443
#>  3 -1.79   2.5  89.5 66443
#>  4 -1.79   3.5  89.5 66443
#>  5 -1.79   4.5  89.5 66443
#>  6 -1.79   5.5  89.5 66443
#>  7 -1.79   6.5  89.5 66443
#>  8 -1.79   7.5  89.5 66443
#>  9 -1.79   8.5  89.5 66443
#> 10 -1.79   9.5  89.5 66443
#> # … with 31,816,790 more rows

ncmeta::nc_dims(f)
#> # A tibble: 4 × 4
#>      id name  length unlim
#>   <int> <chr>  <dbl> <lgl>
#> 1     0 lat      180 FALSE
#> 2     1 lon      360 FALSE
#> 3     2 time     491 TRUE 
#> 4     3 nbnds      2 FALSE
p2 <- ncmeta::nc_dims(f) |> 
  dplyr::filter(name %in% c("lon", "lat", "time")) |> 
  dplyr::summarize(prod(length))

p1 == p2
#>      prod(length)
#> [1,]         TRUE
```

<sup>Created on 2022-11-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
