### ISSUE TITLE
add multiple filtering of the same variable example to README

### ISSUE THREAD

**Issue by everydayduffy** [ropensci/tidync#93]
Hi,

I was a bit stumped when trying to used multiple `hyper_filter` statements to select min/max lat/long values from an nc file. I found the following worked:

```
# coords in EPSG:4326
xmin <- -5
xmax <- 2
ymin <- 50
ymax <- 55

dat <- tidync::tidync(nc_file) %>%
    tidync::hyper_filter(longitude = longitude >= xmin & longitude <= xmax,
                         latitude = latitude >= ymin & latitude <= ymax)
```

whereas this did not:

```
dat <- tidync::tidync(nc_file) %>%
    tidync::hyper_filter(longitude = longitude >= xmin, 
                                  longitude = longitude <= xmax,
                                  latitude = latitude >= ymin, 
                                  latitude = latitude <= ymax)
```

I wondered if you could add something similar to my working example to your README, in case anyone else comes across the same thing. 

Thanks for making a great package!

**Comment by mdsumner** [comment]
Ah thanks, that's right the named arguments must be unique. I'll add an example.

**Comment by everydayduffy** [comment]
Thank you
